# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1385, 1669)
        MainWindow.setAcceptDrops(False)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: #f4f6f7;\n"
"}\n"
"QGroupBox {\n"
"    font-weight: bold;\n"
"    border: 2px solid #bdc3c7;\n"
"    border-radius: 10px;\n"
"    margin-top: 10px;\n"
"}\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    padding: 0 10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(400, -10, 421, 141))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setStyleSheet("color: #2c3e50;\n"
"font-weight: bold;")
        self.title.setTextFormat(QtCore.Qt.AutoText)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.label_init_title = QtWidgets.QGroupBox(self.centralwidget)
        self.label_init_title.setGeometry(QtCore.QRect(70, 140, 481, 471))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_init_title.setFont(font)
        self.label_init_title.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #bdc3c7;\n"
"    border-radius: 10px;\n"
"    background-color: #f2f7f9;\n"
"}")
        self.label_init_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_init_title.setObjectName("label_init_title")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.label_init_title)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(30, 60, 411, 381))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_init_00 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_init_00.setMinimumSize(QtCore.QSize(120, 120))
        self.label_init_00.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_init_00.setFont(font)
        self.label_init_00.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_init_00.setFrameShape(QtWidgets.QFrame.Box)
        self.label_init_00.setAlignment(QtCore.Qt.AlignCenter)
        self.label_init_00.setObjectName("label_init_00")
        self.gridLayout_4.addWidget(self.label_init_00, 0, 0, 1, 1)
        self.label_init_02 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_init_02.setMinimumSize(QtCore.QSize(120, 120))
        self.label_init_02.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_init_02.setFont(font)
        self.label_init_02.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_init_02.setFrameShape(QtWidgets.QFrame.Box)
        self.label_init_02.setAlignment(QtCore.Qt.AlignCenter)
        self.label_init_02.setObjectName("label_init_02")
        self.gridLayout_4.addWidget(self.label_init_02, 0, 2, 1, 1)
        self.label_init_11 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_init_11.setMinimumSize(QtCore.QSize(120, 120))
        self.label_init_11.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_init_11.setFont(font)
        self.label_init_11.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_init_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_init_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_init_11.setObjectName("label_init_11")
        self.gridLayout_4.addWidget(self.label_init_11, 1, 1, 1, 1)
        self.label_init_21 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_init_21.setMinimumSize(QtCore.QSize(120, 120))
        self.label_init_21.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_init_21.setFont(font)
        self.label_init_21.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_init_21.setFrameShape(QtWidgets.QFrame.Box)
        self.label_init_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_init_21.setObjectName("label_init_21")
        self.gridLayout_4.addWidget(self.label_init_21, 2, 1, 1, 1)
        self.label_init_10 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_init_10.setMinimumSize(QtCore.QSize(120, 120))
        self.label_init_10.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_init_10.setFont(font)
        self.label_init_10.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_init_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_init_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_init_10.setObjectName("label_init_10")
        self.gridLayout_4.addWidget(self.label_init_10, 1, 0, 1, 1)
        self.label_init_22 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_init_22.setMinimumSize(QtCore.QSize(120, 120))
        self.label_init_22.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_init_22.setFont(font)
        self.label_init_22.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_init_22.setFrameShape(QtWidgets.QFrame.Box)
        self.label_init_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_init_22.setObjectName("label_init_22")
        self.gridLayout_4.addWidget(self.label_init_22, 2, 2, 1, 1)
        self.label_init_20 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_init_20.setMinimumSize(QtCore.QSize(120, 120))
        self.label_init_20.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_init_20.setFont(font)
        self.label_init_20.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_init_20.setFrameShape(QtWidgets.QFrame.Box)
        self.label_init_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_init_20.setObjectName("label_init_20")
        self.gridLayout_4.addWidget(self.label_init_20, 2, 0, 1, 1)
        self.label_init_12 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_init_12.setMinimumSize(QtCore.QSize(120, 120))
        self.label_init_12.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_init_12.setFont(font)
        self.label_init_12.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_init_12.setFrameShape(QtWidgets.QFrame.Box)
        self.label_init_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_init_12.setObjectName("label_init_12")
        self.gridLayout_4.addWidget(self.label_init_12, 1, 2, 1, 1)
        self.label_init_01 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_init_01.setMinimumSize(QtCore.QSize(120, 120))
        self.label_init_01.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_init_01.setFont(font)
        self.label_init_01.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_init_01.setFrameShape(QtWidgets.QFrame.Box)
        self.label_init_01.setAlignment(QtCore.Qt.AlignCenter)
        self.label_init_01.setObjectName("label_init_01")
        self.gridLayout_4.addWidget(self.label_init_01, 0, 1, 1, 1)
        self.label_goal_title = QtWidgets.QGroupBox(self.centralwidget)
        self.label_goal_title.setGeometry(QtCore.QRect(600, 140, 521, 471))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_goal_title.setFont(font)
        self.label_goal_title.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #bdc3c7;\n"
"    border-radius: 10px;\n"
"    background-color: #f2f7f9;\n"
"}")
        self.label_goal_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_goal_title.setObjectName("label_goal_title")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.label_goal_title)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(60, 60, 410, 380))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_goal_12 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_goal_12.setMinimumSize(QtCore.QSize(120, 120))
        self.label_goal_12.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_goal_12.setFont(font)
        self.label_goal_12.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_goal_12.setFrameShape(QtWidgets.QFrame.Box)
        self.label_goal_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_goal_12.setObjectName("label_goal_12")
        self.gridLayout_2.addWidget(self.label_goal_12, 1, 2, 1, 1)
        self.label_goal_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_goal_10.setMinimumSize(QtCore.QSize(120, 120))
        self.label_goal_10.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_goal_10.setFont(font)
        self.label_goal_10.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_goal_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_goal_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_goal_10.setObjectName("label_goal_10")
        self.gridLayout_2.addWidget(self.label_goal_10, 1, 0, 1, 1)
        self.label_goal_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_goal_11.setMinimumSize(QtCore.QSize(120, 120))
        self.label_goal_11.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_goal_11.setFont(font)
        self.label_goal_11.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_goal_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_goal_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_goal_11.setObjectName("label_goal_11")
        self.gridLayout_2.addWidget(self.label_goal_11, 1, 1, 1, 1)
        self.label_goal_02 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_goal_02.setMinimumSize(QtCore.QSize(120, 120))
        self.label_goal_02.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_goal_02.setFont(font)
        self.label_goal_02.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_goal_02.setFrameShape(QtWidgets.QFrame.Box)
        self.label_goal_02.setAlignment(QtCore.Qt.AlignCenter)
        self.label_goal_02.setObjectName("label_goal_02")
        self.gridLayout_2.addWidget(self.label_goal_02, 0, 2, 1, 1)
        self.label_goal_00 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_goal_00.setMinimumSize(QtCore.QSize(120, 120))
        self.label_goal_00.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_goal_00.setFont(font)
        self.label_goal_00.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_goal_00.setFrameShape(QtWidgets.QFrame.Box)
        self.label_goal_00.setAlignment(QtCore.Qt.AlignCenter)
        self.label_goal_00.setObjectName("label_goal_00")
        self.gridLayout_2.addWidget(self.label_goal_00, 0, 0, 1, 1)
        self.label_goal_01 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_goal_01.setMinimumSize(QtCore.QSize(120, 120))
        self.label_goal_01.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_goal_01.setFont(font)
        self.label_goal_01.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_goal_01.setFrameShape(QtWidgets.QFrame.Box)
        self.label_goal_01.setAlignment(QtCore.Qt.AlignCenter)
        self.label_goal_01.setObjectName("label_goal_01")
        self.gridLayout_2.addWidget(self.label_goal_01, 0, 1, 1, 1)
        self.label_goal_20 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_goal_20.setMinimumSize(QtCore.QSize(120, 120))
        self.label_goal_20.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_goal_20.setFont(font)
        self.label_goal_20.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_goal_20.setFrameShape(QtWidgets.QFrame.Box)
        self.label_goal_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_goal_20.setObjectName("label_goal_20")
        self.gridLayout_2.addWidget(self.label_goal_20, 2, 0, 1, 1)
        self.label_goal_21 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_goal_21.setMinimumSize(QtCore.QSize(120, 120))
        self.label_goal_21.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_goal_21.setFont(font)
        self.label_goal_21.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_goal_21.setFrameShape(QtWidgets.QFrame.Box)
        self.label_goal_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_goal_21.setObjectName("label_goal_21")
        self.gridLayout_2.addWidget(self.label_goal_21, 2, 1, 1, 1)
        self.label_goal_22 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_goal_22.setMinimumSize(QtCore.QSize(120, 120))
        self.label_goal_22.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_goal_22.setFont(font)
        self.label_goal_22.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_goal_22.setFrameShape(QtWidgets.QFrame.Box)
        self.label_goal_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_goal_22.setObjectName("label_goal_22")
        self.gridLayout_2.addWidget(self.label_goal_22, 2, 2, 1, 1)
        self.combo_algorithm = QtWidgets.QComboBox(self.centralwidget)
        self.combo_algorithm.setGeometry(QtCore.QRect(950, 20, 241, 91))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.combo_algorithm.setFont(font)
        self.combo_algorithm.setObjectName("combo_algorithm")
        self.combo_algorithm.addItem("")
        self.combo_algorithm.addItem("")
        self.combo_algorithm.addItem("")
        self.label_current_title = QtWidgets.QGroupBox(self.centralwidget)
        self.label_current_title.setGeometry(QtCore.QRect(70, 740, 1071, 491))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_current_title.setFont(font)
        self.label_current_title.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #bdc3c7;\n"
"    border-radius: 10px;\n"
"    background-color: #f2f7f9;\n"
"}")
        self.label_current_title.setObjectName("label_current_title")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.label_current_title)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(30, 60, 401, 380))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_cur_00 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_cur_00.setMinimumSize(QtCore.QSize(120, 120))
        self.label_cur_00.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_cur_00.setFont(font)
        self.label_cur_00.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_cur_00.setFrameShape(QtWidgets.QFrame.Box)
        self.label_cur_00.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cur_00.setObjectName("label_cur_00")
        self.gridLayout_5.addWidget(self.label_cur_00, 0, 0, 1, 1)
        self.label_cur_01 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_cur_01.setMinimumSize(QtCore.QSize(120, 120))
        self.label_cur_01.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_cur_01.setFont(font)
        self.label_cur_01.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_cur_01.setFrameShape(QtWidgets.QFrame.Box)
        self.label_cur_01.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cur_01.setObjectName("label_cur_01")
        self.gridLayout_5.addWidget(self.label_cur_01, 0, 1, 1, 1)
        self.label_cur_02 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_cur_02.setMinimumSize(QtCore.QSize(120, 120))
        self.label_cur_02.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_cur_02.setFont(font)
        self.label_cur_02.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_cur_02.setFrameShape(QtWidgets.QFrame.Box)
        self.label_cur_02.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cur_02.setObjectName("label_cur_02")
        self.gridLayout_5.addWidget(self.label_cur_02, 0, 2, 1, 1)
        self.label_cur_12 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_cur_12.setMinimumSize(QtCore.QSize(120, 120))
        self.label_cur_12.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_cur_12.setFont(font)
        self.label_cur_12.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_cur_12.setFrameShape(QtWidgets.QFrame.Box)
        self.label_cur_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cur_12.setObjectName("label_cur_12")
        self.gridLayout_5.addWidget(self.label_cur_12, 1, 2, 1, 1)
        self.label_cur_11 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_cur_11.setMinimumSize(QtCore.QSize(120, 120))
        self.label_cur_11.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_cur_11.setFont(font)
        self.label_cur_11.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_cur_11.setFrameShape(QtWidgets.QFrame.Box)
        self.label_cur_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cur_11.setObjectName("label_cur_11")
        self.gridLayout_5.addWidget(self.label_cur_11, 1, 1, 1, 1)
        self.label_cur_10 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_cur_10.setMinimumSize(QtCore.QSize(120, 120))
        self.label_cur_10.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_cur_10.setFont(font)
        self.label_cur_10.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_cur_10.setFrameShape(QtWidgets.QFrame.Box)
        self.label_cur_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cur_10.setObjectName("label_cur_10")
        self.gridLayout_5.addWidget(self.label_cur_10, 1, 0, 1, 1)
        self.label_cur_20 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_cur_20.setMinimumSize(QtCore.QSize(120, 120))
        self.label_cur_20.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_cur_20.setFont(font)
        self.label_cur_20.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_cur_20.setFrameShape(QtWidgets.QFrame.Box)
        self.label_cur_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cur_20.setObjectName("label_cur_20")
        self.gridLayout_5.addWidget(self.label_cur_20, 2, 0, 1, 1)
        self.label_cur_21 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_cur_21.setMinimumSize(QtCore.QSize(120, 120))
        self.label_cur_21.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_cur_21.setFont(font)
        self.label_cur_21.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_cur_21.setFrameShape(QtWidgets.QFrame.Box)
        self.label_cur_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cur_21.setObjectName("label_cur_21")
        self.gridLayout_5.addWidget(self.label_cur_21, 2, 1, 1, 1)
        self.label_cur_22 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_cur_22.setMinimumSize(QtCore.QSize(120, 120))
        self.label_cur_22.setMaximumSize(QtCore.QSize(120, 120))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_cur_22.setFont(font)
        self.label_cur_22.setStyleSheet("background-color: #ecf0f1;\n"
"border: 2px solid #bdc3c7;\n"
"border-radius: 10px;\n"
"font-size: 100px;\n"
"font-weight: bold;\n"
"color: #2c3e50;")
        self.label_cur_22.setFrameShape(QtWidgets.QFrame.Box)
        self.label_cur_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cur_22.setObjectName("label_cur_22")
        self.gridLayout_5.addWidget(self.label_cur_22, 2, 2, 1, 1)
        self.label_step_info = QtWidgets.QLabel(self.label_current_title)
        self.label_step_info.setGeometry(QtCore.QRect(550, 70, 321, 131))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_step_info.setFont(font)
        self.label_step_info.setObjectName("label_step_info")
        self.progress_bar = QtWidgets.QProgressBar(self.label_current_title)
        self.progress_bar.setGeometry(QtCore.QRect(550, 270, 481, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.progress_bar.setFont(font)
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.label_memory_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.label_memory_2.setGeometry(QtCore.QRect(70, 1250, 1081, 151))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_memory_2.setFont(font)
        self.label_memory_2.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #bdc3c7;\n"
"    border-radius: 10px;\n"
"    background-color: #f2f7f9;\n"
"}")
        self.label_memory_2.setObjectName("label_memory_2")
        self.label_time = QtWidgets.QLabel(self.label_memory_2)
        self.label_time.setGeometry(QtCore.QRect(520, 60, 261, 46))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")
        self.label_expanded = QtWidgets.QLabel(self.label_memory_2)
        self.label_expanded.setGeometry(QtCore.QRect(240, 60, 227, 46))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_expanded.setFont(font)
        self.label_expanded.setObjectName("label_expanded")
        self.label_steps = QtWidgets.QLabel(self.label_memory_2)
        self.label_steps.setGeometry(QtCore.QRect(40, 60, 145, 46))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_steps.setFont(font)
        self.label_steps.setObjectName("label_steps")
        self.label_memory = QtWidgets.QLabel(self.label_memory_2)
        self.label_memory.setGeometry(QtCore.QRect(810, 60, 221, 46))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_memory.setFont(font)
        self.label_memory.setObjectName("label_memory")
        self.btn_generate = QtWidgets.QPushButton(self.centralwidget)
        self.btn_generate.setGeometry(QtCore.QRect(70, 650, 311, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_generate.setFont(font)
        self.btn_generate.setObjectName("btn_generate")
        self.btn_solve = QtWidgets.QPushButton(self.centralwidget)
        self.btn_solve.setGeometry(QtCore.QRect(400, 650, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_solve.setFont(font)
        self.btn_solve.setObjectName("btn_solve")
        self.btn_pause = QtWidgets.QPushButton(self.centralwidget)
        self.btn_pause.setGeometry(QtCore.QRect(730, 650, 211, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_pause.setFont(font)
        self.btn_pause.setObjectName("btn_pause")
        self.btn_reset = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reset.setGeometry(QtCore.QRect(960, 650, 181, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.btn_reset.setFont(font)
        self.btn_reset.setObjectName("btn_reset")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(140, 1450, 641, 111))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1385, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "八数码求解器"))
        self.label_init_title.setTitle(_translate("MainWindow", "初始状态"))
        self.label_init_00.setText(_translate("MainWindow", "TextLabel"))
        self.label_init_02.setText(_translate("MainWindow", "TextLabel"))
        self.label_init_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_init_21.setText(_translate("MainWindow", "TextLabel"))
        self.label_init_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_init_22.setText(_translate("MainWindow", "TextLabel"))
        self.label_init_20.setText(_translate("MainWindow", "TextLabel"))
        self.label_init_12.setText(_translate("MainWindow", "TextLabel"))
        self.label_init_01.setText(_translate("MainWindow", "TextLabel"))
        self.label_goal_title.setTitle(_translate("MainWindow", "目标状态"))
        self.label_goal_12.setText(_translate("MainWindow", "TextLabel"))
        self.label_goal_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_goal_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_goal_02.setText(_translate("MainWindow", "TextLabel"))
        self.label_goal_00.setText(_translate("MainWindow", "TextLabel"))
        self.label_goal_01.setText(_translate("MainWindow", "TextLabel"))
        self.label_goal_20.setText(_translate("MainWindow", "TextLabel"))
        self.label_goal_21.setText(_translate("MainWindow", "TextLabel"))
        self.label_goal_22.setText(_translate("MainWindow", "TextLabel"))
        self.combo_algorithm.setItemText(0, _translate("MainWindow", "BFS"))
        self.combo_algorithm.setItemText(1, _translate("MainWindow", "A*"))
        self.combo_algorithm.setItemText(2, _translate("MainWindow", "IDA*"))
        self.label_current_title.setTitle(_translate("MainWindow", "当前搜索状态"))
        self.label_cur_00.setText(_translate("MainWindow", "TextLabel"))
        self.label_cur_01.setText(_translate("MainWindow", "TextLabel"))
        self.label_cur_02.setText(_translate("MainWindow", "TextLabel"))
        self.label_cur_12.setText(_translate("MainWindow", "TextLabel"))
        self.label_cur_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_cur_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_cur_20.setText(_translate("MainWindow", "TextLabel"))
        self.label_cur_21.setText(_translate("MainWindow", "TextLabel"))
        self.label_cur_22.setText(_translate("MainWindow", "TextLabel"))
        self.label_step_info.setText(_translate("MainWindow", "步骤：0/0"))
        self.label_memory_2.setTitle(_translate("MainWindow", "信息统计"))
        self.label_time.setText(_translate("MainWindow", "耗时：0 ms"))
        self.label_expanded.setText(_translate("MainWindow", "扩展结点：0"))
        self.label_steps.setText(_translate("MainWindow", "步数：0"))
        self.label_memory.setText(_translate("MainWindow", "内存：0"))
        self.btn_generate.setText(_translate("MainWindow", "🎲 生成新问题"))
        self.btn_solve.setText(_translate("MainWindow", "▶ 开始求解"))
        self.btn_pause.setText(_translate("MainWindow", "⏸ 暂停"))
        self.btn_reset.setText(_translate("MainWindow", "🔄 重置"))
        self.label_status.setText(_translate("MainWindow", "💡 提示: 点击「生成新问题」开始"))
